const BASE = "/api";

export async function api(path, options = {}) {
  const res = await fetch(BASE + path, {
    credentials: "include",
    headers: { "content-type": "application/json", ...(options.headers || {}) },
    ...options,
  });
  const data = await res.json();
  if (!res.ok) throw new Error(data.error || `HTTP ${res.status}`);
  return data;
}

export function packToMarkdown(pack) {
  const lines = [`# Context pack — "${pack.query}"`, ""];
  if (pack.capabilities.length) {
    lines.push("## Recommended capabilities");
    for (const c of pack.capabilities) {
      lines.push(`### ${c.title} (${c.team}${c.owner ? `, ${c.owner}` : ""})`);
      lines.push(c.content);
      if (c.whyItWorked) lines.push(`*Why it worked:* ${c.whyItWorked}`);
      lines.push("");
    }
  }
  if (pack.beliefs.length) {
    lines.push("## Adopted org practice");
    for (const b of pack.beliefs) lines.push(`- ${b.content}`);
    lines.push("");
  }
  if (pack.claims.length) {
    lines.push("## Grounded knowledge");
    for (const k of pack.claims) lines.push(`- ${k.content} _(${k.sourceTier || "unknown"} source)_`);
    lines.push("");
  }
  if (pack.cautions.length) {
    lines.push("## Cautions");
    for (const c of pack.cautions) lines.push(`- CONTESTED — ${c.topic}: ${c.summary}`);
    lines.push("");
  }
  lines.push(`_Generated by Engrammic Org Memory at ${pack.generatedAt}_`);
  return lines.join("\n");
}
